config/routes.rb
Rails.application.routes.draw do
  resources :reviews
  resources :users
  
  root 'main#index'
  
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  get 'signup' => 'users#new'
  delete 'logout' => 'sessions#destroy'

end

app/models/review.rb
class Review < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user
  
  def current_user 
    @current_user ||= User.find(session[:user_id]) if session[:user_id] 
  end

  def require_user 
    redirect_to '/login' unless current_user 
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  before_action :require_user, only: [:index]	
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  def create
    @user = User.find_by_email(params[:session][:email])
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      redirect_to '/'
    else
      redirect_to 'login'
    end 
  end
  def destroy 
    session[:user_id] = nil 
    redirect_to '/' 
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :check_for_cancel, :only => [:create]
  def new 
    @user = User.new
  end
  def create
    @user = User.new(user_params) 
    if @user.save 
      session[:user_id] = @user.id 
      redirect_to '/' 
    else 
      redirect_to '/signup' 
    end 
  end
  private; def user_params
    params.require(:user).permit(:first_name,:last_name, :email, :password)
  end
  private; def check_for_cancel
    if params[:commit] == "Cancel"
      redirect_to '/'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Simple Reviews</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  
  <div class="header_menu">
  <div class="user_menu">
  <% if current_user %>
  <ul class="inline">
    <li><%= current_user.email %></li>
    <li><%= link_to "Log out", logout_path, method: "delete" %></li>
  </ul>
  <% else %>
  <ul>
    <li><%= link_to "Log in", 'login' %></li>
    <li><%= link_to "Register", 'signup' %></li>
  </lu>
  <% end %>
  </div>
</div>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/main/index.html.erb
<div class="main">
	<h1>Adequate Enjoyment</h1>
	<p>A simple application for simple video game reviews.</p>
	
	<%= link_to 'Register', new_user_path %>
</div>

app/views/users/new.html.erb
<div class="main">
  <%= form_for :user, url: users_path do |user| %>  
  <div class="field"> 
    <%= user.text_field :first_name, :placeholder => :first_name %> 
  </div> 
    <div class="field"> 
    <%= user.text_field :last_name, :placeholder => :last_name %> 
  </div> 
    <div class="field"> 
    <%= user.email_field :email, :placeholder => :email %> 
  </div> 
    <div class="field"> 
    <%= user.password_field :password, :placeholder => :password %> 
  </div> 
  <ul class="inline">
  <li><div class="actions"> 
    <%= user.submit "Create" %> 
  </div> 
  </li>
  <li>
  <div class="actions">
    <%= user.submit "Cancel" %>
  </div>
  </li>
  </ul>
<% end %>
</div>